### ISSUE TITLE
finalize recaptcha integration (in the frontend)

### ISSUE THREAD

**Issue by gorzala** [dancier/show-dancer#24]
Hey Boss,
please do the following:

- Check if it is really useful to use the current npm module for captcha integration
- Make the token form googles recaptcha end up in the request to the registration-endpoint
- check if the way we did it yesterday is not too dirty ;-)
- work on already existing branch "recaptcha"

Best
Marc

**Comment by gorzala** [comment]
I changed the openapi-description for you, to let you know how the backend expects the field to be named.

**Comment by gorzala** [comment]
Please:
 * let the user enter the password (and maybe the mail adresss) twice?
 * Check if both versions are equal to each other
 * only when both is entered with the above mentioned constrain, show the captcha box (between the input fields and the submitt button)
 * Why am I asking you for this?
 * the captche token is only valid for two minutes. If the token is validated in the backend after two minutes, the validation will fail. So I want to have the user use the captcha as the last stept before submitting :-)

**Comment by halbekanne** [comment]
Done with #23
